services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client/vite-project
      args:
        VITE_API_URL: http://localhost:5000
    depends_on:
      - server
    ports:
      - "8080:8080"
